[package]
name = "dewey"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
glob = "0.3.1"
native-tls = "0.2.12"
rand = "0.8.5"
serde = "1.0.206"
serde_json = "1.0.122"
sha2 = "0.10.8"
